version: '2'
services:
  sphinx:
    image: philoles/sphinx:2.2.10
    ports:
      - "9312:9312"
      - "9306:9306"
    volumes:
      - /song/sphinx/idx:/var/idx/sphinx
      - /song/sphinx/log:/var/log/sphinx
      - /song/sphinx/lib:/var/lib/sphinx
      - /song/sphinx/run:/var/run/sphinx
      - /song/sphinx/diz:/var/diz/sphinx
      - /song/sphinx/sphinx.conf:/usr/local/etc/sphinx.conf
    restart: always
    container_name: sphinx
    hostname: sphinx
    networks:
      - song
    command: ["indexall.sh"]

networks:
  song:
    external: true 